# Generated by Django 4.2.5 on 2023-09-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
