# Generated by Django 4.2.5 on 2023-09-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
