# Generated by Django 4.2.5 on 2023-09-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_remove_user_created_at_remove_user_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Registers',
        ),
    ]
